//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.05 at 11:29:45 PM CDT 
//


package com.tegik.addenda.soriana.sources.ackerrorapl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ackErrorApplicationIdentification">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="entityType" type="{http://www.w3.org/2001/XMLSchema}short"/>
 *                   &lt;element name="uniqueCreatorIdentification" type="{http://www.w3.org/2001/XMLSchema}byte"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ApplicationInformation">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="deliveryDatePresent" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="ReferenceNumber">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="referenceIdentification" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Buyer">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nameAndAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Seller">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="nameAndAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="messageError">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="errorDescription">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}byte" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="contentVersion" type="{http://www.w3.org/2001/XMLSchema}float" />
 *       &lt;attribute name="documentStructureVersion" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="creationDate" type="{http://www.w3.org/2001/XMLSchema}int" />
 *       &lt;attribute name="documentStatus" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "ackErrorApplicationIdentification",
    "applicationInformation",
    "referenceNumber",
    "buyer",
    "seller",
    "messageError"
})
@XmlRootElement(name = "AckErrorApplication")
public class AckErrorApplication {

    @XmlElement(required = true)
    protected AckErrorApplication.AckErrorApplicationIdentification ackErrorApplicationIdentification;
    @XmlElement(name = "ApplicationInformation", required = true)
    protected AckErrorApplication.ApplicationInformation applicationInformation;
    @XmlElement(name = "ReferenceNumber", required = true)
    protected AckErrorApplication.ReferenceNumber referenceNumber;
    @XmlElement(name = "Buyer", required = true)
    protected AckErrorApplication.Buyer buyer;
    @XmlElement(name = "Seller", required = true)
    protected AckErrorApplication.Seller seller;
    @XmlElement(required = true)
    protected AckErrorApplication.MessageError messageError;
    @XmlAttribute(name = "contentVersion")
    protected Float contentVersion;
    @XmlAttribute(name = "documentStructureVersion")
    protected String documentStructureVersion;
    @XmlAttribute(name = "creationDate")
    protected Integer creationDate;
    @XmlAttribute(name = "documentStatus")
    protected String documentStatus;

    /**
     * Gets the value of the ackErrorApplicationIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link AckErrorApplication.AckErrorApplicationIdentification }
     *     
     */
    public AckErrorApplication.AckErrorApplicationIdentification getAckErrorApplicationIdentification() {
        return ackErrorApplicationIdentification;
    }

    /**
     * Sets the value of the ackErrorApplicationIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link AckErrorApplication.AckErrorApplicationIdentification }
     *     
     */
    public void setAckErrorApplicationIdentification(AckErrorApplication.AckErrorApplicationIdentification value) {
        this.ackErrorApplicationIdentification = value;
    }

    /**
     * Gets the value of the applicationInformation property.
     * 
     * @return
     *     possible object is
     *     {@link AckErrorApplication.ApplicationInformation }
     *     
     */
    public AckErrorApplication.ApplicationInformation getApplicationInformation() {
        return applicationInformation;
    }

    /**
     * Sets the value of the applicationInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link AckErrorApplication.ApplicationInformation }
     *     
     */
    public void setApplicationInformation(AckErrorApplication.ApplicationInformation value) {
        this.applicationInformation = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link AckErrorApplication.ReferenceNumber }
     *     
     */
    public AckErrorApplication.ReferenceNumber getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link AckErrorApplication.ReferenceNumber }
     *     
     */
    public void setReferenceNumber(AckErrorApplication.ReferenceNumber value) {
        this.referenceNumber = value;
    }

    /**
     * Gets the value of the buyer property.
     * 
     * @return
     *     possible object is
     *     {@link AckErrorApplication.Buyer }
     *     
     */
    public AckErrorApplication.Buyer getBuyer() {
        return buyer;
    }

    /**
     * Sets the value of the buyer property.
     * 
     * @param value
     *     allowed object is
     *     {@link AckErrorApplication.Buyer }
     *     
     */
    public void setBuyer(AckErrorApplication.Buyer value) {
        this.buyer = value;
    }

    /**
     * Gets the value of the seller property.
     * 
     * @return
     *     possible object is
     *     {@link AckErrorApplication.Seller }
     *     
     */
    public AckErrorApplication.Seller getSeller() {
        return seller;
    }

    /**
     * Sets the value of the seller property.
     * 
     * @param value
     *     allowed object is
     *     {@link AckErrorApplication.Seller }
     *     
     */
    public void setSeller(AckErrorApplication.Seller value) {
        this.seller = value;
    }

    /**
     * Gets the value of the messageError property.
     * 
     * @return
     *     possible object is
     *     {@link AckErrorApplication.MessageError }
     *     
     */
    public AckErrorApplication.MessageError getMessageError() {
        return messageError;
    }

    /**
     * Sets the value of the messageError property.
     * 
     * @param value
     *     allowed object is
     *     {@link AckErrorApplication.MessageError }
     *     
     */
    public void setMessageError(AckErrorApplication.MessageError value) {
        this.messageError = value;
    }

    /**
     * Gets the value of the contentVersion property.
     * 
     * @return
     *     possible object is
     *     {@link Float }
     *     
     */
    public Float getContentVersion() {
        return contentVersion;
    }

    /**
     * Sets the value of the contentVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link Float }
     *     
     */
    public void setContentVersion(Float value) {
        this.contentVersion = value;
    }

    /**
     * Gets the value of the documentStructureVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentStructureVersion() {
        return documentStructureVersion;
    }

    /**
     * Sets the value of the documentStructureVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentStructureVersion(String value) {
        this.documentStructureVersion = value;
    }

    /**
     * Gets the value of the creationDate property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCreationDate() {
        return creationDate;
    }

    /**
     * Sets the value of the creationDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCreationDate(Integer value) {
        this.creationDate = value;
    }

    /**
     * Gets the value of the documentStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocumentStatus() {
        return documentStatus;
    }

    /**
     * Sets the value of the documentStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocumentStatus(String value) {
        this.documentStatus = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="entityType" type="{http://www.w3.org/2001/XMLSchema}short"/>
     *         &lt;element name="uniqueCreatorIdentification" type="{http://www.w3.org/2001/XMLSchema}byte"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "entityType",
        "uniqueCreatorIdentification"
    })
    public static class AckErrorApplicationIdentification {

        protected short entityType;
        protected byte uniqueCreatorIdentification;

        /**
         * Gets the value of the entityType property.
         * 
         */
        public short getEntityType() {
            return entityType;
        }

        /**
         * Sets the value of the entityType property.
         * 
         */
        public void setEntityType(short value) {
            this.entityType = value;
        }

        /**
         * Gets the value of the uniqueCreatorIdentification property.
         * 
         */
        public byte getUniqueCreatorIdentification() {
            return uniqueCreatorIdentification;
        }

        /**
         * Sets the value of the uniqueCreatorIdentification property.
         * 
         */
        public void setUniqueCreatorIdentification(byte value) {
            this.uniqueCreatorIdentification = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="deliveryDatePresent" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deliveryDatePresent"
    })
    public static class ApplicationInformation {

        @XmlElement(required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar deliveryDatePresent;

        /**
         * Gets the value of the deliveryDatePresent property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDeliveryDatePresent() {
            return deliveryDatePresent;
        }

        /**
         * Sets the value of the deliveryDatePresent property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDeliveryDatePresent(XMLGregorianCalendar value) {
            this.deliveryDatePresent = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nameAndAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameAndAddress"
    })
    public static class Buyer {

        @XmlElement(required = true)
        protected String nameAndAddress;

        /**
         * Gets the value of the nameAndAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameAndAddress() {
            return nameAndAddress;
        }

        /**
         * Sets the value of the nameAndAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameAndAddress(String value) {
            this.nameAndAddress = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="errorCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="errorDescription">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="sequence" type="{http://www.w3.org/2001/XMLSchema}byte" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "errorCode",
        "errorDescription"
    })
    public static class MessageError {

        @XmlElement(required = true)
        protected String errorCode;
        @XmlElement(required = true)
        protected AckErrorApplication.MessageError.ErrorDescription errorDescription;
        @XmlAttribute(name = "sequence")
        protected Byte sequence;

        /**
         * Gets the value of the errorCode property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getErrorCode() {
            return errorCode;
        }

        /**
         * Sets the value of the errorCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setErrorCode(String value) {
            this.errorCode = value;
        }

        /**
         * Gets the value of the errorDescription property.
         * 
         * @return
         *     possible object is
         *     {@link AckErrorApplication.MessageError.ErrorDescription }
         *     
         */
        public AckErrorApplication.MessageError.ErrorDescription getErrorDescription() {
            return errorDescription;
        }

        /**
         * Sets the value of the errorDescription property.
         * 
         * @param value
         *     allowed object is
         *     {@link AckErrorApplication.MessageError.ErrorDescription }
         *     
         */
        public void setErrorDescription(AckErrorApplication.MessageError.ErrorDescription value) {
            this.errorDescription = value;
        }

        /**
         * Gets the value of the sequence property.
         * 
         * @return
         *     possible object is
         *     {@link Byte }
         *     
         */
        public Byte getSequence() {
            return sequence;
        }

        /**
         * Sets the value of the sequence property.
         * 
         * @param value
         *     allowed object is
         *     {@link Byte }
         *     
         */
        public void setSequence(Byte value) {
            this.sequence = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "text"
        })
        public static class ErrorDescription {

            @XmlElement(required = true)
            protected String text;

            /**
             * Gets the value of the text property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getText() {
                return text;
            }

            /**
             * Sets the value of the text property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setText(String value) {
                this.text = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="referenceIdentification" type="{http://www.w3.org/2001/XMLSchema}int"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "referenceIdentification"
    })
    public static class ReferenceNumber {

        protected int referenceIdentification;

        /**
         * Gets the value of the referenceIdentification property.
         * 
         */
        public int getReferenceIdentification() {
            return referenceIdentification;
        }

        /**
         * Sets the value of the referenceIdentification property.
         * 
         */
        public void setReferenceIdentification(int value) {
            this.referenceIdentification = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="nameAndAddress" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "nameAndAddress"
    })
    public static class Seller {

        @XmlElement(required = true)
        protected String nameAndAddress;

        /**
         * Gets the value of the nameAndAddress property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNameAndAddress() {
            return nameAndAddress;
        }

        /**
         * Sets the value of the nameAndAddress property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNameAndAddress(String value) {
            this.nameAndAddress = value;
        }

    }

}
