//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.05 at 11:29:45 PM CDT 
//


package com.tegik.addenda.soriana.sources.ackerrorapl;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.tegik.addenda.soriana.sources package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.tegik.addenda.soriana.sources
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link AckErrorApplication }
     * 
     */
    public AckErrorApplication createAckErrorApplication() {
        return new AckErrorApplication();
    }

    /**
     * Create an instance of {@link AckErrorApplication.MessageError }
     * 
     */
    public AckErrorApplication.MessageError createAckErrorApplicationMessageError() {
        return new AckErrorApplication.MessageError();
    }

    /**
     * Create an instance of {@link AckErrorApplication.AckErrorApplicationIdentification }
     * 
     */
    public AckErrorApplication.AckErrorApplicationIdentification createAckErrorApplicationAckErrorApplicationIdentification() {
        return new AckErrorApplication.AckErrorApplicationIdentification();
    }

    /**
     * Create an instance of {@link AckErrorApplication.ApplicationInformation }
     * 
     */
    public AckErrorApplication.ApplicationInformation createAckErrorApplicationApplicationInformation() {
        return new AckErrorApplication.ApplicationInformation();
    }

    /**
     * Create an instance of {@link AckErrorApplication.ReferenceNumber }
     * 
     */
    public AckErrorApplication.ReferenceNumber createAckErrorApplicationReferenceNumber() {
        return new AckErrorApplication.ReferenceNumber();
    }

    /**
     * Create an instance of {@link AckErrorApplication.Buyer }
     * 
     */
    public AckErrorApplication.Buyer createAckErrorApplicationBuyer() {
        return new AckErrorApplication.Buyer();
    }

    /**
     * Create an instance of {@link AckErrorApplication.Seller }
     * 
     */
    public AckErrorApplication.Seller createAckErrorApplicationSeller() {
        return new AckErrorApplication.Seller();
    }

    /**
     * Create an instance of {@link AckErrorApplication.MessageError.ErrorDescription }
     * 
     */
    public AckErrorApplication.MessageError.ErrorDescription createAckErrorApplicationMessageErrorErrorDescription() {
        return new AckErrorApplication.MessageError.ErrorDescription();
    }

}
