//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.5-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.03 at 02:20:43 PM CDT 
//


package com.tegik.addenda.soriana.piedecamion.sources;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded">
 *         &lt;element name="Remision">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Proveedor" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Remision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Consecutivo" type="{http://www.w3.org/2001/XMLSchema}Short"/>
 *                   &lt;element name="FechaRemision" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="Tienda" type="{http://www.w3.org/2001/XMLSchema}Short"/>
 *                   &lt;element name="TipoMoneda" type="{http://www.w3.org/2001/XMLSchema}Short"/>
 *                   &lt;element name="TipoBulto" type="{http://www.w3.org/2001/XMLSchema}Short"/>
 *                   &lt;element name="EntregaMercancia" type="{http://www.w3.org/2001/XMLSchema}Short"/>
 *                   &lt;element name="CumpleReqFiscales" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
 *                   &lt;element name="CantidadBultos" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="Subtotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="IEPS" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="IVA" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="OtrosImpuestos" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="CantidadPedidos" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="FechaEntregaMercancia" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="Cita" type="{http://www.w3.org/2001/XMLSchema}Integer" minOccurs="0"/>
 *                   &lt;element name="FolioNotaEntrada" type="{http://www.w3.org/2001/XMLSchema}Integer" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pedimento">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Proveedor" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Remision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="Pedimento" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Aduana" type="{http://www.w3.org/2001/XMLSchema}Short"/>
 *                   &lt;element name="AgenteAduanal" type="{http://www.w3.org/2001/XMLSchema}Short"/>
 *                   &lt;element name="TipoPedimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FechaPedimento" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="FechaReciboLaredo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="FechaBillOfLading" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Pedidos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Proveedor" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Remision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FolioPedido" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Tienda" type="{http://www.w3.org/2001/XMLSchema}Short"/>
 *                   &lt;element name="CantidadArticulos" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="PedidoEmitidoProveedor" minOccurs="0">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *                         &lt;minLength value="1"/>
 *                         &lt;maxLength value="2"/>
 *                         &lt;enumeration value="SI"/>
 *                         &lt;enumeration value="NO"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="Articulos">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Proveedor" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Remision" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="FolioPedido" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
 *                   &lt;element name="Tienda" type="{http://www.w3.org/2001/XMLSchema}Short"/>
 *                   &lt;element name="Codigo" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="CantidadUnidadCompra" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="CostoNetoUnidadCompra" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="PorcentajeIEPS" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                   &lt;element name="PorcentajeIVA" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "remisionOrPedimentoOrPedidos"
})
@XmlRootElement(name = "DSCargaRemisionProv")
public class DSCargaRemisionProv {

    @XmlElements({
        @XmlElement(name = "Remision", type = DSCargaRemisionProv.Remision.class),
        @XmlElement(name = "Pedimento", type = DSCargaRemisionProv.Pedimento.class),
        @XmlElement(name = "Pedidos", type = DSCargaRemisionProv.Pedidos.class),
        @XmlElement(name = "Articulos", type = DSCargaRemisionProv.Articulos.class)
    })
    protected List<Object> remisionOrPedimentoOrPedidos;

    /**
     * Gets the value of the remisionOrPedimentoOrPedidos property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the remisionOrPedimentoOrPedidos property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRemisionOrPedimentoOrPedidos().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DSCargaRemisionProv.Remision }
     * {@link DSCargaRemisionProv.Pedimento }
     * {@link DSCargaRemisionProv.Pedidos }
     * {@link DSCargaRemisionProv.Articulos }
     * 
     * 
     */
    public List<Object> getRemisionOrPedimentoOrPedidos() {
        if (remisionOrPedimentoOrPedidos == null) {
            remisionOrPedimentoOrPedidos = new ArrayList<Object>();
        }
        return this.remisionOrPedimentoOrPedidos;
    }
    
    public void addRemisionOrPedimentoOrPedidos(Object object){
      if (remisionOrPedimentoOrPedidos == null) {
        remisionOrPedimentoOrPedidos = new ArrayList<Object>();
    }
      remisionOrPedimentoOrPedidos.add(object);
      
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Proveedor" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Remision" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FolioPedido" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Tienda" type="{http://www.w3.org/2001/XMLSchema}Short"/>
     *         &lt;element name="Codigo" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="CantidadUnidadCompra" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="CostoNetoUnidadCompra" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="PorcentajeIEPS" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="PorcentajeIVA" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "proveedor",
        "remision",
        "folioPedido",
        "tienda",
        "codigo",
        "cantidadUnidadCompra",
        "costoNetoUnidadCompra",
        "porcentajeIEPS",
        "porcentajeIVA"
    })
    public static class Articulos {

        @XmlElement(name = "Proveedor")
        protected Integer proveedor;
        @XmlElement(name = "Remision", required = true)
        protected String remision;
        @XmlElement(name = "FolioPedido")
        protected Integer folioPedido;
        @XmlElement(name = "Tienda")
        protected Short tienda;
        @XmlElement(name = "Codigo", required = true)
        protected BigDecimal codigo;
        @XmlElement(name = "CantidadUnidadCompra", required = true)
        protected BigDecimal cantidadUnidadCompra;
        @XmlElement(name = "CostoNetoUnidadCompra", required = true)
        protected BigDecimal costoNetoUnidadCompra;
        @XmlElement(name = "PorcentajeIEPS", required = true)
        protected BigDecimal porcentajeIEPS;
        @XmlElement(name = "PorcentajeIVA", required = true)
        protected BigDecimal porcentajeIVA;

        /**
         * Gets the value of the proveedor property.
         * 
         */
        public Integer getProveedor() {
            return proveedor;
        }

        /**
         * Sets the value of the proveedor property.
         * 
         */
        public void setProveedor(Integer value) throws Exception {
          if(value == null )
            throw new Exception("El numero de proveedor esta vacio");
          this.proveedor = value;
        }

        /**
         * Gets the value of the remision property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemision() {
            return remision;
        }

        /**
         * Sets the value of the remision property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemision(String value) throws Exception {
          if(value == null )
            throw new Exception("La remisión esta vacio");
          this.remision = value;
        }

        /**
         * Gets the value of the folioPedido property.
         * 
         */
        public Integer getFolioPedido() {
            return folioPedido;
        }

        /**
         * Sets the value of the folioPedido property.
         * 
         */
        public void setFolioPedido(Integer value) throws Exception {
          if(value == null )
            throw new Exception("El folio de la remisión esta vacio");
          this.folioPedido = value;
        }

        /**
         * Gets the value of the tienda property.
         * 
         */
        public Short getTienda() {
            return tienda;
        }

        /**
         * Sets the value of the tienda property.
         * 
         */
        public void setTienda(Short value) throws Exception {
          if(value == null )
            throw new Exception("El número de la tienda esta vacio");
          this.tienda = value;
        }

        /**
         * Gets the value of the codigo property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCodigo() {
            return codigo;
        }

        /**
         * Sets the value of the codigo property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCodigo(BigDecimal value) throws Exception {
          if(value == null )
            throw new Exception("El codigo esta vacio");
          this.codigo = value;
        }

        /**
         * Gets the value of the cantidadUnidadCompra property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCantidadUnidadCompra() {
            return cantidadUnidadCompra;
        }

        /**
         * Sets the value of the cantidadUnidadCompra property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCantidadUnidadCompra(BigDecimal value) throws Exception {
          if(value == null )
            throw new Exception("La cantidad de unidad de compra esta vacio");
          this.cantidadUnidadCompra = value;
        }

        /**
         * Gets the value of the costoNetoUnidadCompra property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCostoNetoUnidadCompra() {
            return costoNetoUnidadCompra;
        }

        /**
         * Sets the value of the costoNetoUnidadCompra property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCostoNetoUnidadCompra(BigDecimal value)  throws Exception {
          if(value == null )
            throw new Exception("El costo neto unitario esta vacio");
          this.costoNetoUnidadCompra = value;
        }

        /**
         * Gets the value of the porcentajeIEPS property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPorcentajeIEPS() {
            return porcentajeIEPS;
        }

        /**
         * Sets the value of the porcentajeIEPS property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPorcentajeIEPS(BigDecimal value) throws Exception  {
          if(value == null )
            throw new Exception("El Porcentaje IEPS esta vacio");
           this.porcentajeIEPS = value;
        }

        /**
         * Gets the value of the porcentajeIVA property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getPorcentajeIVA() {
            return porcentajeIVA;
        }

        /**
         * Sets the value of the porcentajeIVA property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setPorcentajeIVA(BigDecimal value)  throws Exception {
          if(value == null )
            throw new Exception("El Porcentaje de IVA esta vacio");
           this.porcentajeIVA = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Proveedor" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Remision" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FolioPedido" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Tienda" type="{http://www.w3.org/2001/XMLSchema}Short"/>
     *         &lt;element name="CantidadArticulos" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="PedidoEmitidoProveedor" minOccurs="0">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
     *               &lt;minLength value="1"/>
     *               &lt;maxLength value="2"/>
     *               &lt;enumeration value="SI"/>
     *               &lt;enumeration value="NO"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "proveedor",
        "remision",
        "folioPedido",
        "tienda",
        "cantidadArticulos",
        "pedidoEmitidoProveedor"
    })
    public static class Pedidos {

        @XmlElement(name = "Proveedor")
        protected Integer proveedor;
        @XmlElement(name = "Remision", required = true)
        protected String remision;
        @XmlElement(name = "FolioPedido")
        protected Integer folioPedido;
        @XmlElement(name = "Tienda")
        protected Short tienda;
        @XmlElement(name = "CantidadArticulos")
        protected Integer cantidadArticulos;
        @XmlElement(name = "PedidoEmitidoProveedor")
        @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
        protected String pedidoEmitidoProveedor;

        /**
         * Gets the value of the proveedor property.
         * 
         */
        public Integer getProveedor() {
            return proveedor;
        }

        /**
         * Sets the value of the proveedor property.
         * 
         */
        public void setProveedor(Integer value) throws Exception  {
          if(value == null) throw new Exception("El proveedor esta vacio");
            this.proveedor = value;
        }

        /**
         * Gets the value of the remision property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemision() {
            return remision;
        }

        /**
         * Sets the value of the remision property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemision(String value) throws Exception {
          if(value == null) throw new Exception("La remisión esta vacio");

            this.remision = value;
        }

        /**
         * Gets the value of the folioPedido property.
         * 
         */
        public Integer getFolioPedido() {
            return folioPedido;
        }

        /**
         * Sets the value of the folioPedido property.
         * 
         */
        public void setFolioPedido(Integer value) throws Exception {
          if(value == null) throw new Exception("El folio del pedido esta vacio");
            this.folioPedido = value;
        }

        /**
         * Gets the value of the tienda property.
         * 
         */
        public Short getTienda() {
            return tienda;
        }

        /**
         * Sets the value of the tienda property.
         * 
         */
        public void setTienda(Short value) throws Exception {
          if(value == null) throw new Exception("El número de tienda esta vacio");
            this.tienda = value;
        }

        /**
         * Gets the value of the cantidadArticulos property.
         * 
         */
        public Integer getCantidadArticulos() {
            return cantidadArticulos;
        }

        /**
         * Sets the value of the cantidadArticulos property.
         * 
         */
        public void setCantidadArticulos(Integer value) throws Exception {
          if(value == null) throw new Exception("La cantidad de articulos esta vacio");
            this.cantidadArticulos = value;
        }

        /**
         * Gets the value of the pedidoEmitidoProveedor property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getPedidoEmitidoProveedor() {
            return pedidoEmitidoProveedor;
        }

        /**
         * Sets the value of the pedidoEmitidoProveedor property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setPedidoEmitidoProveedor(String value)  throws Exception {
          if(value == null) throw new Exception("El pedido emitido proveedor esta vacio");

            this.pedidoEmitidoProveedor = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Proveedor" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Remision" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Pedimento" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Aduana" type="{http://www.w3.org/2001/XMLSchema}Short"/>
     *         &lt;element name="AgenteAduanal" type="{http://www.w3.org/2001/XMLSchema}Short"/>
     *         &lt;element name="TipoPedimento" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="FechaPedimento" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="FechaReciboLaredo" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="FechaBillOfLading" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "proveedor",
        "remision",
        "pedimento",
        "aduana",
        "agenteAduanal",
        "tipoPedimento",
        "fechaPedimento",
        "fechaReciboLaredo",
        "fechaBillOfLading"
    })
    public static class Pedimento {

        @XmlElement(name = "Proveedor")
        protected Integer proveedor;
        @XmlElement(name = "Remision", required = true)
        protected String remision;
        @XmlElement(name = "Pedimento")
        protected Integer pedimento;
        @XmlElement(name = "Aduana")
        protected Short aduana;
        @XmlElement(name = "AgenteAduanal")
        protected Short agenteAduanal;
        @XmlElement(name = "TipoPedimento", required = true)
        protected String tipoPedimento;
        @XmlElement(name = "FechaPedimento", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fechaPedimento;
        @XmlElement(name = "FechaReciboLaredo", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fechaReciboLaredo;
        @XmlElement(name = "FechaBillOfLading", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fechaBillOfLading;

        /**
         * Gets the value of the proveedor property.
         * 
         */
        public Integer getProveedor() {
            return proveedor;
        }

        /**
         * Sets the value of the proveedor property.
         * 
         */
        public void setProveedor(Integer value) throws Exception {
          if(value == null) throw new Exception("El proveedor esta vacio");
            this.proveedor = value;
        }

        /**
         * Gets the value of the remision property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemision() {
            return remision;
        }

        /**
         * Sets the value of the remision property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemision(String value) throws Exception {
          if(value == null) throw new Exception("El número de remisión esta vacio");
            this.remision = value;
        }

        /**
         * Gets the value of the pedimento property.
         * 
         */
        public Integer getPedimento() {
            return pedimento;
        }

        /**
         * Sets the value of the pedimento property.
         * 
         */
        public void setPedimento(Integer value) throws Exception {
          if(value == null) throw new Exception("El numero de pedimento esta vacio");
            this.pedimento = value;
        }

        /**
         * Gets the value of the aduana property.
         * 
         */
        public Short getAduana() {
            return aduana;
        }

        /**
         * Sets the value of the aduana property.
         * 
         */
        public void setAduana(Short value) throws Exception  {
          if(value == null) throw new Exception("El numero de aduana esta vacio");

            this.aduana = value;
        }

        /**
         * Gets the value of the agenteAduanal property.
         * 
         */
        public Short getAgenteAduanal() {
            return agenteAduanal;
        }

        /**
         * Sets the value of the agenteAduanal property.
         * 
         */
        public void setAgenteAduanal(Short value) throws Exception{
          if(value == null) throw new Exception("El numero de agente aduanal esta vacio");
            this.agenteAduanal = value;
        }

        /**
         * Gets the value of the tipoPedimento property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTipoPedimento() {
            return tipoPedimento;
        }

        /**
         * Sets the value of the tipoPedimento property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTipoPedimento(String value)  throws Exception{
          if(value == null) throw new Exception("El tipo de pedimento esta vacio");
            this.tipoPedimento = value;
        }

        /**
         * Gets the value of the fechaPedimento property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaPedimento() {
            return fechaPedimento;
        }

        /**
         * Sets the value of the fechaPedimento property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaPedimento(XMLGregorianCalendar value) throws Exception{
          if(value == null) throw new Exception("La fecha de pedimento esta vacio");
            this.fechaPedimento = value;
        }

        /**
         * Gets the value of the fechaReciboLaredo property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaReciboLaredo() {         
            return fechaReciboLaredo;
        }

        /**
         * Sets the value of the fechaReciboLaredo property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaReciboLaredo(XMLGregorianCalendar value) throws Exception {
          if(value == null) throw new Exception("La fecha de recibo esta vacio");
            this.fechaReciboLaredo = value;
        }

        /**
         * Gets the value of the fechaBillOfLading property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaBillOfLading() {
            return fechaBillOfLading;
        }

        /**
         * Sets the value of the fechaBillOfLading property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaBillOfLading(XMLGregorianCalendar value) throws Exception {
          if(value == null) throw new Exception("La fecha de biil of landing esta vacio");
            this.fechaBillOfLading = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Proveedor" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="Remision" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="Consecutivo" type="{http://www.w3.org/2001/XMLSchema}Short"/>
     *         &lt;element name="FechaRemision" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="Tienda" type="{http://www.w3.org/2001/XMLSchema}Short"/>
     *         &lt;element name="TipoMoneda" type="{http://www.w3.org/2001/XMLSchema}Short"/>
     *         &lt;element name="TipoBulto" type="{http://www.w3.org/2001/XMLSchema}Short"/>
     *         &lt;element name="EntregaMercancia" type="{http://www.w3.org/2001/XMLSchema}Short"/>
     *         &lt;element name="CumpleReqFiscales" type="{http://www.w3.org/2001/XMLSchema}Boolean"/>
     *         &lt;element name="CantidadBultos" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="Subtotal" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="IEPS" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="IVA" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="OtrosImpuestos" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
     *         &lt;element name="CantidadPedidos" type="{http://www.w3.org/2001/XMLSchema}Integer"/>
     *         &lt;element name="FechaEntregaMercancia" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="Cita" type="{http://www.w3.org/2001/XMLSchema}Integer" minOccurs="0"/>
     *         &lt;element name="FolioNotaEntrada" type="{http://www.w3.org/2001/XMLSchema}Integer" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "proveedor",
        "remision",
        "consecutivo",
        "fechaRemision",
        "tienda",
        "tipoMoneda",
        "tipoBulto",
        "entregaMercancia",
        "cumpleReqFiscales",
        "cantidadBultos",
        "subtotal",
        "descuentos",
        "ieps",
        "iva",
        "otrosImpuestos",
        "total",
        "cantidadPedidos",
        "fechaEntregaMercancia",
        "cita",
        "folioNotaEntrada"
    })
    public static class Remision {

        @XmlElement(name = "Proveedor")
        protected Integer proveedor;
        @XmlElement(name = "Remision", required = true)
        protected String remision;
        @XmlElement(name = "Consecutivo")
        protected Short consecutivo;
        @XmlElement(name = "FechaRemision", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fechaRemision;
        @XmlElement(name = "Tienda")
        protected Short tienda;
        @XmlElement(name = "TipoMoneda")
        protected Short tipoMoneda;
        @XmlElement(name = "TipoBulto")
        protected Short tipoBulto;
        @XmlElement(name = "EntregaMercancia")
        protected Short entregaMercancia;
        @XmlElement(name = "CumpleReqFiscales")
        protected Boolean cumpleReqFiscales;
        @XmlElement(name = "CantidadBultos", required = true)
        protected BigDecimal cantidadBultos;
        @XmlElement(name = "Subtotal", required = true)
        protected BigDecimal subtotal;
        @XmlElement(name = "Descuentos", required = true)
        protected BigDecimal descuentos;
        @XmlElement(name = "IEPS", required = true)
        protected BigDecimal ieps;
        @XmlElement(name = "IVA", required = true)
        protected BigDecimal iva;
        @XmlElement(name = "OtrosImpuestos", required = true)
        protected BigDecimal otrosImpuestos;
        @XmlElement(name = "Total", required = true)
        protected BigDecimal total;
        @XmlElement(name = "CantidadPedidos")
        protected Integer cantidadPedidos;
        @XmlElement(name = "FechaEntregaMercancia", required = true)
        @XmlSchemaType(name = "dateTime")
        protected XMLGregorianCalendar fechaEntregaMercancia;
        @XmlElement(name = "Cita")
        protected Integer cita;
        @XmlElement(name = "FolioNotaEntrada")
        protected Integer folioNotaEntrada;

        /**
         * Gets the value of the proveedor property.
         * 
         */
        public Integer getProveedor() {
            return proveedor;
        }

        /**
         * Sets the value of the proveedor property.
         * 
         */
        public void setProveedor(Integer value) throws Exception  {
          if(value == null) throw new Exception("El proveedor esta vacio");
            this.proveedor = value;
        }

        /**
         * Gets the value of the remision property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRemision() {
            return remision;
        }

        /**
         * Sets the value of the remision property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRemision(String value) throws Exception  {
          if(value == null) throw new Exception("La remision esta vacio");
            this.remision = value;
        }

        /**
         * Gets the value of the consecutivo property.
         * 
         */
        public Short getConsecutivo() {
            return consecutivo;
        }

        /**
         * Sets the value of the consecutivo property.
         * 
         */
        public void setConsecutivo(Short value) throws Exception  {
          if(value == null) throw new Exception("El numero consecutivo esta vacio");
            this.consecutivo = value;
        }

        /**
         * Gets the value of the fechaRemision property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaRemision() {
            return fechaRemision;
        }

        /**
         * Sets the value of the fechaRemision property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaRemision(XMLGregorianCalendar value) throws Exception  {
          if(value == null) throw new Exception("La fecha de remision esta vacio");
            this.fechaRemision = value;
        }

        /**
         * Gets the value of the tienda property.
         * 
         */
        public Short getTienda() {
            return tienda;
        }

        /**
         * Sets the value of the tienda property.
         * 
         */
        public void setTienda(Short value) throws Exception  {
          if(value == null) throw new Exception("El numero de tienda esta vacio");
            this.tienda = value;
        }

        /**
         * Gets the value of the tipoMoneda property.
         * 
         */
        public Short getTipoMoneda() {
            return tipoMoneda;
        }

        /**
         * Sets the value of the tipoMoneda property.
         * 
         */
        public void setTipoMoneda(Short value) throws Exception  {
          if(value == null) throw new Exception("El tipo de moneda esta vacio");
            this.tipoMoneda = value;
        }

        /**
         * Gets the value of the tipoBulto property.
         * 
         */
        public Short getTipoBulto() {
            return tipoBulto;
        }

        /**
         * Sets the value of the tipoBulto property.
         * 
         */
        public void setTipoBulto(Short value) throws Exception  {
          if(value == null) throw new Exception("El tipo de bulto esta vacio");
            this.tipoBulto = value;
        }

        /**
         * Gets the value of the entregaMercancia property.
         * 
         */
        public Short getEntregaMercancia() {
            return entregaMercancia;
        }

        /**
         * Sets the value of the entregaMercancia property.
         * 
         */
        public void setEntregaMercancia(Short value) throws Exception  {
          if(value == null) throw new Exception("La  entrega de mercancia esta vacio");
            this.entregaMercancia = value;
        }

        /**
         * Gets the value of the cumpleReqFiscales property.
         * 
         */
        public Boolean isCumpleReqFiscales() {
            return cumpleReqFiscales;
        }

        /**
         * Sets the value of the cumpleReqFiscales property.
         * 
         */
        public void setCumpleReqFiscales(Boolean value) throws Exception  {
          if(value == null) throw new Exception("Cumple Requisitos Fiscales esta vacio");
            this.cumpleReqFiscales = value;
        }

        /**
         * Gets the value of the cantidadBultos property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getCantidadBultos() {
            return cantidadBultos;
        }

        /**
         * Sets the value of the cantidadBultos property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setCantidadBultos(BigDecimal value) throws Exception  {
          if(value == null) throw new Exception("La cantidad de bultos esta vacio");
            this.cantidadBultos = value;
        }

        /**
         * Gets the value of the subtotal property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSubtotal() {
            return subtotal;
        }

        /**
         * Sets the value of the subtotal property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSubtotal(BigDecimal value) throws Exception  {
          if(value == null) throw new Exception("El subtotal de remision esta vacio");
            this.subtotal = value;
        }
        /**
         * Gets the value of the descuento property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getDescuentos() {
            return descuentos;
        }

        /**
         * Sets the value of the descuentos property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setDescuentos(BigDecimal value) throws Exception  {
          if(value == null) throw new Exception("El descuento de remision esta vacio");
            this.descuentos = value;
        }

        /**
         * Gets the value of the ieps property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getIEPS() {
            return ieps;
        }

        /**
         * Sets the value of the ieps property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setIEPS(BigDecimal value) throws Exception  {
          if(value == null) throw new Exception("El IEPS esta vacio");
            this.ieps = value;
        }

        /**
         * Gets the value of the iva property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getIVA() {
            return iva;
        }

        /**
         * Sets the value of the iva property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setIVA(BigDecimal value) throws Exception  {
          if(value == null) throw new Exception("El IVA  esta vacio");
            this.iva = value;
        }

        /**
         * Gets the value of the otrosImpuestos property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getOtrosImpuestos() {
            return otrosImpuestos;
        }

        /**
         * Sets the value of the otrosImpuestos property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setOtrosImpuestos(BigDecimal value) throws Exception  {
          if(value == null) throw new Exception("El otros impuestos esta vacio");
            this.otrosImpuestos = value;
        }

        /**
         * Gets the value of the total property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getTotal() {
            return total;
        }

        /**
         * Sets the value of the total property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setTotal(BigDecimal value) throws Exception  {
          if(value == null) throw new Exception("El total de remision esta vacio");
            this.total = value;
        }

        /**
         * Gets the value of the cantidadPedidos property.
         * 
         */
        public Integer getCantidadPedidos() {
            return cantidadPedidos;
        }

        /**
         * Sets the value of the cantidadPedidos property.
         * 
         */
        public void setCantidadPedidos(Integer value) throws Exception  {
          if(value == null) throw new Exception("La cantidad pedida esta vacio");
            this.cantidadPedidos = value;
        }

        /**
         * Gets the value of the fechaEntregaMercancia property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getFechaEntregaMercancia() {
            return fechaEntregaMercancia;
        }

        /**
         * Sets the value of the fechaEntregaMercancia property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setFechaEntregaMercancia(XMLGregorianCalendar value) throws Exception  {
          if(value == null) throw new Exception("La fecha de entrega de mercancia esta vacio");
            this.fechaEntregaMercancia = value;
        }

        /**
         * Gets the value of the cita property.
         * 
         * @return
         *     possible object is
         *     {@link Integereger }
         *     
         */
        public Integer getCita() {
            return cita;
        }

        /**
         * Sets the value of the cita property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integereger }
         *     
         */
        public void setCita(Integer value) {
            this.cita = value;
        }

        /**
         * Gets the value of the folioNotaEntrada property.
         * 
         * @return
         *     possible object is
         *     {@link Integereger }
         *     
         */
        public Integer getFolioNotaEntrada() {
            return folioNotaEntrada;
        }

        /**
         * Sets the value of the folioNotaEntrada property.
         * 
         * @param value
         *     allowed object is
         *     {@link Integereger }
         *     
         */
        public void setFolioNotaEntrada(Integer value) throws Exception  {
          if(value == null) throw new Exception("El folio de nota de entrada esta vacio");
            this.folioNotaEntrada = value;
        }

    }

}
